<?php

/**
 * Validate public/lib/entrants.php against data/contest-matches.json and the
 * frozen id ledger data/entrant-ids.json, then emit the review views
 * data/entrants.json and data/entrants.md.
 *
 * public/lib/entrants.php is GENERATED by scripts/gen-entrants.php (which also
 * writes the ledger). This script never writes it — it only checks it and
 * rebuilds the derived views. Exits non-zero on any validation failure.
 *
 * Run from the repo root: php scripts/build-entrants.php
 */

declare(strict_types=1);

$ROOT = dirname(__DIR__);
require_once $ROOT . '/public/lib/entrants.php';

$J = json_decode((string) file_get_contents($ROOT . '/data/contest-matches.json'), true, 512, JSON_THROW_ON_ERROR);

$POOLS  = ['character', 'game', 'series', 'rivalry', 'year'];
$errors = [];
$err    = function (string $m) use (&$errors): void {
    $errors[] = $m;
};

/* ---- index the registry: "pool\0name" => id ---- */
$byKey = [];
foreach (ENTRANTS as $id => $e) {
    $byKey[$e['type'] . "\0" . $e['name']] = $id;
}

/* ---- walk the data: attestation, per-contest string sets, first-appearance ---- */
$att          = [];   // "pool\0canon" => [first_poll, first_contest, n, nOff]
$contestStr   = [];   // contest label => set of normalized raw entrant strings
$rawByPool    = [];   // pool => set of normalized raw entrant strings seen in the data
$firstPollByK = [];   // "pool\0canon" => earliest poll id
$slots        = 0;
$byPoll       = [];
foreach ($J as $label => $blk) {
    foreach ($blk['matches'] as $m) {
        $pool = $m['type'] ?? $blk['type'];
        foreach ($m['entrants'] as $raw) {
            ++$slots;
            $norm                      = entrant_norm($raw);
            $canon                     = entrant_canon($pool, $raw);
            $key                       = $pool . "\0" . $canon;
            $contestStr[$label][$norm] = true;
            $rawByPool[$pool][$norm]   = true;
            $byPoll[$m['poll']][]      = $key;
            if (!isset($att[$key])) {
                $att[$key] = ['first_poll' => $m['poll'], 'first_contest' => $label, 'n' => 0, 'nOff' => 0];
            }
            ++$att[$key]['n'];
            $att[$key]['nOff'] += empty($m['official']) ? 0 : 1;
        }
    }
}
ksort($byPoll);
foreach ($byPoll as $poll => $keys) {
    foreach ($keys as $k) {
        $firstPollByK[$k] ??= $poll;
    }
}

/* ---- 1. ids match the frozen ledger (data/entrant-ids.json) exactly ---- */
$ledgerFile = $ROOT . '/data/entrant-ids.json';
if (!is_file($ledgerFile)) {
    $err('data/entrant-ids.json missing — run `php scripts/gen-entrants.php` first');
} else {
    $ledger   = [];   // "type\0name" => id
    $ledgerId = [];    // id => "type\0name"
    foreach (json_decode((string) file_get_contents($ledgerFile), true, 512, JSON_THROW_ON_ERROR) as [$t, $n, $i]) {
        $lk = $t . "\0" . $n;
        $i  = (int) $i;
        if (isset($ledger[$lk])) {
            $err("ledger: duplicate (type,name) {$t} / {$n}");
        }
        if (isset($ledgerId[$i])) {
            $err("ledger: id {$i} used twice");
        }
        $ledger[$lk]  = $i;
        $ledgerId[$i] = $lk;
    }
    foreach (ENTRANTS as $id => $e) {
        $lk = $e['type'] . "\0" . $e['name'];
        if (!isset($ledger[$lk])) {
            $err("id {$id} ({$e['type']} / {$e['name']}) is not in the ledger");
        } elseif ($ledger[$lk] !== $id) {
            $err("id mismatch for {$e['type']} / {$e['name']}: ENTRANTS says {$id}, ledger says {$ledger[$lk]}");
        }
    }
}

/* ---- 2. names normalized & non-empty; (type,name) unique; type known ---- */
$seenName = [];
foreach (ENTRANTS as $id => $e) {
    if ($e['name'] === '' || entrant_norm($e['name']) !== $e['name']) {
        $err("id {$id}: name not normalized or empty: " . json_encode($e['name']));
    }
    if (!in_array($e['type'], $POOLS, true)) {
        $err("id {$id}: unknown type '{$e['type']}'");
    }
    $k = $e['type'] . "\0" . $e['name'];
    if (isset($seenName[$k])) {
        $err("duplicate (type,name): {$e['type']} / {$e['name']} (#{$seenName[$k]} and #{$id})");
    }
    $seenName[$k] = $id;
}

/* ---- 3. alias map integrity ---- */
$revVariant = [];
foreach (ENTRANT_ALIASES as $pool => $map) {
    foreach ($map as $canon => $vars) {
        if (!isset($byKey[$pool . "\0" . $canon])) {
            $err("alias canonical not in ENTRANTS: [{$pool}] {$canon}");
        }
        foreach ($vars as $v) {
            if (entrant_norm($v) !== $v) {
                $err("alias variant not normalized: [{$pool}] " . json_encode($v));
            }
            if ($v === $canon) {
                $err("alias variant equals its canonical: [{$pool}] {$v}");
            }
            if (isset($byKey[$pool . "\0" . $v])) {
                $err("alias variant is also a standalone entity: [{$pool}] {$v}");
            }
            if (isset($revVariant[$pool . "\0" . $v]) && $revVariant[$pool . "\0" . $v] !== $canon) {
                $err("alias variant resolves to two canonicals: [{$pool}] {$v}");
            }
            if (!isset($rawByPool[$pool][$v])) {
                $err("alias variant never appears in the data (stale): [{$pool}] {$v}");
            }
            $revVariant[$pool . "\0" . $v] = $canon;
        }
    }
}

/* ---- 4. coverage: every attested (pool,canon) is a registered entity ---- */
foreach (array_keys($att) as $key) {
    if (!isset($byKey[$key])) {
        $err('uncovered entrant: ' . str_replace("\0", ' / ', $key));
    }
}

/* ---- 5. phantoms: every registered entity is attested in the data ---- */
foreach (array_diff(array_keys($byKey), array_keys($att)) as $key) {
    $err('phantom entity (never attested): ' . str_replace("\0", ' / ', $key));
}

/* ---- 6. never-merge: members present, distinct ids ---- */
foreach (ENTRANT_NEVER_MERGE as $g) {
    $gids = [];
    foreach ($g as $n) {
        $id = null;
        foreach (ENTRANTS as $eid => $e) {
            if ($e['name'] === $n) {
                $id = $eid;

                break;
            }
        }
        if ($id === null) {
            $err('never-merge member missing from ENTRANTS: ' . $n);
        } else {
            $gids[] = $id;
        }
    }
    if (count(array_unique($gids)) !== count($g)) {
        $err('never-merge group does not resolve to distinct ids: ' . implode(' | ', $g));
    }
}

/* ---- 7. era invariant: a bare variant that a later contest fully disambiguated
        must be absent from that contest (never ambiguous there) ---- */
foreach (ENTRANT_ERA_SCOPED as $es) {
    if (!isset($revVariant[$es['pool'] . "\0" . $es['variant']])) {
        $err("era-scoped rule names '{$es['variant']}' but it is not an alias variant in [{$es['pool']}] (stale rule)");
    }
    if (isset($contestStr[$es['disambiguated_in']][$es['variant']])) {
        $err("era invariant broken: bare '{$es['variant']}' appears in {$es['disambiguated_in']}, which spells out every reading");
    }
}

/* ---- 8. ids in nondecreasing first-appearance-poll order. Holds today because
        every id was assigned chronologically. It can legitimately break later if
        a missed entity in an OLD contest is appended at max+1 by the ledger's
        freeze pass — if that happens, downgrade this to a warning. ---- */
$rowsById = ENTRANTS;
ksort($rowsById);
$prev = 0;
foreach ($rowsById as $id => $e) {
    $fp = $firstPollByK[$e['type'] . "\0" . $e['name']] ?? null;
    if ($fp === null) {
        continue;   // already reported by the phantom check
    }
    if ($fp < $prev) {
        $err("id {$id} ({$e['name']}) first appears at poll {$fp}, out of chronological order");

        break;
    }
    $prev = max($prev, $fp);
}

/* ---- stop here on any failure ---- */
if ($errors) {
    fwrite(STDERR, 'VALIDATION FAILED (' . count($errors) . "):\n");
    foreach ($errors as $e) {
        fwrite(STDERR, "  - {$e}\n");
    }
    exit(1);
}

/* ---- assemble the derived rows ---- */
$aliasesByCanon = [];
foreach (ENTRANT_ALIASES as $pool => $map) {
    foreach ($map as $canon => $vars) {
        $aliasesByCanon[$pool . "\0" . $canon] = array_values($vars);
    }
}
$entities = [];
foreach ($rowsById as $id => $e) {
    $key = $e['type'] . "\0" . $e['name'];
    $a   = $att[$key];
    $row = [
        'id'                   => $id,
        'name'                 => $e['name'],
        'type'                 => $e['type'],
        'first_poll'           => $a['first_poll'],
        'first_contest'        => $a['first_contest'],
        'appearances'          => $a['n'],
        'official_appearances' => $a['nOff'],
    ];
    if (!empty($aliasesByCanon[$key])) {
        $row['aliases'] = $aliasesByCanon[$key];
    }
    $entities[] = $row;
}
$byPoolCount = [];
foreach ($POOLS as $p) {
    $byPoolCount[$p] = count(array_filter($entities, fn ($r) => $r['type'] === $p));
}

/* ---- emit data/entrants.json ---- */
$json = [
    'generated'    => gmdate('Y-m-d H:i') . ' UTC',
    'entity_count' => count($entities),
    'by_pool'      => $byPoolCount,
    'never_merge'  => array_map('array_values', ENTRANT_NEVER_MERGE),
    'entities'     => $entities,
];
file_put_contents(
    $ROOT . '/data/entrants.json',
    json_encode($json, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . "\n"
);

/* ---- emit data/entrants.md ---- */
$mdc  = fn (string $s): string => str_replace('|', '\|', $s);
$slug = fn (string $s): string => strtolower(preg_replace('/[^a-z0-9]+/i', '-', trim($s)));
$md   = [];
$md[] = '# Canonical Entrant Registry';
$md[] = '';
$md[] = "_Generated {$json['generated']} — do not edit by hand. Source of truth is";
$md[] = '`public/lib/entrants.php`; rebuild + validate with `php scripts/build-entrants.php`._';
$md[] = '';
$md[] = sprintf(
    '**%d entities** — %s.',
    count($entities),
    implode(', ', array_map(fn ($p) => "{$byPoolCount[$p]} {$p}", $POOLS))
);
$md[] = '';
$md[] = 'IDs are order of first appearance by poll id (alphabetical within a poll) and are';
$md[] = 'frozen. `first seen` is the first contest / poll an entity (any spelling) appears in.';
$md[] = '';
foreach ($POOLS as $pool) {
    $rows = array_values(array_filter($entities, fn ($r) => $r['type'] === $pool));
    $md[] = '## ' . ucfirst($pool) . ' (' . count($rows) . ')';
    $md[] = '';
    $md[] = '| id | name | aliases | first seen | matches (official) |';
    $md[] = '|--:|:--|:--|:--|--:|';
    foreach ($rows as $r) {
        $md[] = sprintf(
            '| %d | %s | %s | %s #%d | %d (%d) |',
            $r['id'],
            $mdc($r['name']),
            $mdc(implode(', ', $r['aliases'] ?? [])),
            $mdc($r['first_contest']),
            $r['first_poll'],
            $r['appearances'],
            $r['official_appearances']
        );
    }
    $md[] = '';
}
$md[] = '## Never merge';
$md[] = '';
$md[] = 'Look-alikes kept as separate ids on purpose (the build asserts they never collapse):';
$md[] = '';
foreach (ENTRANT_NEVER_MERGE as $g) {
    $md[] = '- ' . implode(' &nbsp;|&nbsp; ', array_map($mdc, $g));
}
$md[] = '';
file_put_contents($ROOT . '/data/entrants.md', implode("\n", $md) . "\n");

/* ---- report ---- */
fwrite(STDERR, "wrote data/entrants.json  data/entrants.md\n");
fwrite(STDERR, sprintf(
    "%d entities — %s · %d aliased · coverage %d/%d · OK\n",
    count($entities),
    implode(' ', array_map(fn ($p) => "{$p}=" . $byPoolCount[$p], $POOLS)),
    count($aliasesByCanon),
    $slots,
    $slots
));
exit(0);
