<?php

/**
 * GENERATED FILE — do not edit directly. It is produced by
 * `php scripts/gen-entrants.php` from data/contest-matches.json plus the
 * curation arrays ($ALIAS / $NEVER_MERGE / $ERA_SCOPED) in that script. To
 * change an alias, a never-merge group, etc., edit gen-entrants.php and re-run.
 *
 * Canonical entrant registry — the identity layer for contest entrants.
 *
 * ENTRANTS         id => ['name', 'type']. id = order of first appearance by
 *                  poll id (alphabetical within a poll). type is the pool.
 * ENTRANT_ALIASES  pool => canonical => [DB spelling variants that resolve to it].
 * ENTRANT_NEVER_MERGE / ENTRANT_ERA_SCOPED / ENTRANT_NON
 *                  read only by scripts/build-entrants.php (validation).
 *
 * entrant_norm()   normalization contract (decode entities, fold ellipsis,
 *                  collapse whitespace, trim) — matches build-contest-matches.php.
 * entrant_canon()  entrant_norm() + resolve an alias to its canonical name.
 *
 * `php scripts/build-entrants.php` validates this file and emits the review
 * views data/entrants.{json,md}. Rationale: tmp/entrant-analysis/DECISIONS.md.
 */

declare(strict_types=1);

/** pool => canonical name => [DB spelling variants]. Change these in
 *  scripts/gen-entrants.php, not here. build-entrants.php checks every canonical
 *  exists in ENTRANTS and every variant appears in the data. */
const ENTRANT_ALIASES = [
    'character' => [
        'Aerith Gainsborough'    => ['Aeris', 'Aeris Gainsborough'],
        'Albert Wesker'          => ['Wesker'],
        'Cecil Harvey'           => ['Cecil'],
        'Chun-Li'                => ['Chun Li'],
        'Dr. Robotnik'           => ['Dr. Ivo "Eggman" Robotnik'],
        'Isaac (Golden Sun)'     => ['Isaac'],
        'Ken Masters'            => ['Ken'],
        'Knuckles the Echidna'   => ['Knuckles'],
        'Miles "Tails" Prower'   => ['Miles \'Tails\' Prower'],
        'PaRappa The Rapper'     => ['PaRappa'],
        'Prince of Persia'       => ['The Prince of Persia'],
        'Proto Man'              => ['Protoman'],
        'Ryu'                    => ['Ryu (Street Fighter)'],
        'Samus Aran'             => ['Samus'],
        'Terra Branford'         => ['Terra'],
        'The King of All Cosmos' => ['King of all Cosmos'],
        'Tifa Lockhart'          => ['Tifa Lockheart'],
        'Vivi'                   => ['Vivi Ornitier'],
        'Zero (Mega Man X)'      => ['Zero'],
        'Zidane Tribal'          => ['Zidane'],
    ],
    'game' => [
        'EarthBound'              => ['Earthbound'],
        'The World Ends With You' => ['The World Ends with You'],
    ],
    'rivalry' => [
        'Chell vs. GLaDOS'           => ['Chell vs. GlaDOS'],
        'Cloud Strife vs. Sephiroth' => ['Cloud vs. Sephiroth'],
    ],
];

const ENTRANTS = [
    /* ---- character (406): ids 1-823 ---- */
    1   => ['name' => 'Mario', 'type' => 'character'],
    2   => ['name' => 'Servbot', 'type' => 'character'],
    3   => ['name' => 'Morrigan Aensland', 'type' => 'character'],
    4   => ['name' => 'Spyro the Dragon', 'type' => 'character'],
    5   => ['name' => 'Aya Brea', 'type' => 'character'],
    6   => ['name' => 'Terry Bogard', 'type' => 'character'],
    7   => ['name' => 'Bub', 'type' => 'character'],
    8   => ['name' => 'Donkey Kong', 'type' => 'character'],
    9   => ['name' => 'Alucard', 'type' => 'character'],
    10  => ['name' => 'Miles "Tails" Prower', 'type' => 'character'],
    11  => ['name' => 'Duke Nukem', 'type' => 'character'],
    12  => ['name' => 'Iori Yagami', 'type' => 'character'],
    13  => ['name' => 'PaRappa The Rapper', 'type' => 'character'],
    14  => ['name' => 'Pikachu', 'type' => 'character'],
    15  => ['name' => 'Cloud Strife', 'type' => 'character'],
    16  => ['name' => 'Fox McCloud', 'type' => 'character'],
    17  => ['name' => 'Chop Chop Master Onion', 'type' => 'character'],
    18  => ['name' => 'Lara Croft', 'type' => 'character'],
    19  => ['name' => 'Guybrush Threepwood', 'type' => 'character'],
    20  => ['name' => 'Ryo Hazuki', 'type' => 'character'],
    21  => ['name' => 'Crono', 'type' => 'character'],
    22  => ['name' => 'Simon Belmont', 'type' => 'character'],
    23  => ['name' => 'Dante', 'type' => 'character'],
    24  => ['name' => 'Q*Bert', 'type' => 'character'],
    25  => ['name' => 'Aerith Gainsborough', 'type' => 'character'],
    26  => ['name' => 'Kasumi', 'type' => 'character'],
    27  => ['name' => 'Gordon Freeman', 'type' => 'character'],
    28  => ['name' => 'Tina Armstrong', 'type' => 'character'],
    29  => ['name' => 'Akira Yuki', 'type' => 'character'],
    30  => ['name' => 'Knuckles the Echidna', 'type' => 'character'],
    31  => ['name' => 'Solid Snake', 'type' => 'character'],
    32  => ['name' => 'Squall Leonhart', 'type' => 'character'],
    33  => ['name' => 'Goemon', 'type' => 'character'],
    34  => ['name' => 'Pac-Man', 'type' => 'character'],
    35  => ['name' => 'Abe', 'type' => 'character'],
    36  => ['name' => 'Kyo Kusanagi', 'type' => 'character'],
    37  => ['name' => 'Kazuya Mishima', 'type' => 'character'],
    38  => ['name' => 'Scorpion', 'type' => 'character'],
    39  => ['name' => 'Dirk the Daring', 'type' => 'character'],
    40  => ['name' => 'Max Payne', 'type' => 'character'],
    41  => ['name' => 'Bomberman', 'type' => 'character'],
    42  => ['name' => 'Kane', 'type' => 'character'],
    43  => ['name' => 'Jill Valentine', 'type' => 'character'],
    44  => ['name' => 'Kirby', 'type' => 'character'],
    45  => ['name' => 'Raziel', 'type' => 'character'],
    46  => ['name' => 'Strider Hiryu', 'type' => 'character'],
    47  => ['name' => 'Link', 'type' => 'character'],
    48  => ['name' => 'Little Mac', 'type' => 'character'],
    49  => ['name' => 'Pitfall Harry', 'type' => 'character'],
    50  => ['name' => 'Sonic the Hedgehog', 'type' => 'character'],
    51  => ['name' => 'Claire Redfield', 'type' => 'character'],
    52  => ['name' => 'Tidus', 'type' => 'character'],
    53  => ['name' => 'Ken Masters', 'type' => 'character'],
    54  => ['name' => 'Samus Aran', 'type' => 'character'],
    55  => ['name' => 'CATS', 'type' => 'character'],
    56  => ['name' => 'Ryu', 'type' => 'character'],
    57  => ['name' => 'Mega Man', 'type' => 'character'],
    58  => ['name' => 'Ms. Pac-Man', 'type' => 'character'],
    59  => ['name' => 'Mr. Driller', 'type' => 'character'],
    60  => ['name' => 'Serious Sam', 'type' => 'character'],
    61  => ['name' => 'Gabe Logan', 'type' => 'character'],
    62  => ['name' => 'Sephiroth', 'type' => 'character'],
    63  => ['name' => 'Crash Bandicoot', 'type' => 'character'],
    64  => ['name' => 'Ulala', 'type' => 'character'],
    65  => ['name' => 'AiAi', 'type' => 'character'],
    66  => ['name' => 'Ganondorf', 'type' => 'character'],
    67  => ['name' => 'Magus', 'type' => 'character'],
    68  => ['name' => 'Sam Fisher', 'type' => 'character'],
    69  => ['name' => 'Luigi', 'type' => 'character'],
    70  => ['name' => 'Ratchet', 'type' => 'character'],
    71  => ['name' => 'KOS-MOS', 'type' => 'character'],
    72  => ['name' => 'Isaac (Golden Sun)', 'type' => 'character'],
    73  => ['name' => 'Auron', 'type' => 'character'],
    74  => ['name' => 'Bowser', 'type' => 'character'],
    75  => ['name' => 'Ness', 'type' => 'character'],
    76  => ['name' => 'Conker', 'type' => 'character'],
    77  => ['name' => 'Yoshi', 'type' => 'character'],
    78  => ['name' => 'Sora', 'type' => 'character'],
    79  => ['name' => 'Felix', 'type' => 'character'],
    80  => ['name' => 'Master Chief', 'type' => 'character'],
    81  => ['name' => 'Zero (Mega Man X)', 'type' => 'character'],
    82  => ['name' => 'Captain Olimar', 'type' => 'character'],
    83  => ['name' => 'Shadow the Hedgehog', 'type' => 'character'],
    84  => ['name' => 'Wario', 'type' => 'character'],
    85  => ['name' => 'Kefka', 'type' => 'character'],
    86  => ['name' => 'Tom Nook', 'type' => 'character'],
    87  => ['name' => 'Ramza Beoulve', 'type' => 'character'],
    88  => ['name' => 'Raiden', 'type' => 'character'],
    89  => ['name' => 'Yuna', 'type' => 'character'],
    90  => ['name' => 'Vyse', 'type' => 'character'],
    91  => ['name' => 'Kite', 'type' => 'character'],
    92  => ['name' => 'Tommy Vercetti', 'type' => 'character'],
    93  => ['name' => 'Zelda', 'type' => 'character'],
    94  => ['name' => 'Mr. Resetti', 'type' => 'character'],
    160 => ['name' => 'Luca Blight', 'type' => 'character'],
    161 => ['name' => 'JC Denton', 'type' => 'character'],
    162 => ['name' => 'Earthworm Jim', 'type' => 'character'],
    163 => ['name' => 'Proto Man', 'type' => 'character'],
    164 => ['name' => 'Frog', 'type' => 'character'],
    165 => ['name' => 'Liquid Snake', 'type' => 'character'],
    166 => ['name' => 'Tanner', 'type' => 'character'],
    167 => ['name' => 'Laharl', 'type' => 'character'],
    168 => ['name' => 'Kain', 'type' => 'character'],
    169 => ['name' => 'Jak', 'type' => 'character'],
    170 => ['name' => 'Vivi', 'type' => 'character'],
    171 => ['name' => 'Sly Cooper', 'type' => 'character'],
    172 => ['name' => 'Viewtiful Joe', 'type' => 'character'],
    173 => ['name' => 'HK-47', 'type' => 'character'],
    174 => ['name' => 'Ryu Hayabusa', 'type' => 'character'],
    175 => ['name' => 'Pyramid Head', 'type' => 'character'],
    176 => ['name' => 'Andross', 'type' => 'character'],
    177 => ['name' => 'Sigma', 'type' => 'character'],
    178 => ['name' => 'Nemesis', 'type' => 'character'],
    179 => ['name' => 'Revolver Ocelot', 'type' => 'character'],
    180 => ['name' => 'Dr. Wily', 'type' => 'character'],
    181 => ['name' => 'Ultros', 'type' => 'character'],
    182 => ['name' => 'Ramirez', 'type' => 'character'],
    183 => ['name' => 'Ghaleon', 'type' => 'character'],
    184 => ['name' => 'Vergil', 'type' => 'character'],
    185 => ['name' => 'Lavos', 'type' => 'character'],
    186 => ['name' => 'Mother Brain', 'type' => 'character'],
    187 => ['name' => 'Officer Tenpenny', 'type' => 'character'],
    188 => ['name' => 'Mithos', 'type' => 'character'],
    189 => ['name' => 'Albert Wesker', 'type' => 'character'],
    190 => ['name' => 'Albedo', 'type' => 'character'],
    191 => ['name' => 'M. Bison', 'type' => 'character'],
    192 => ['name' => 'Diablo', 'type' => 'character'],
    193 => ['name' => 'Ridley', 'type' => 'character'],
    194 => ['name' => 'Giygas', 'type' => 'character'],
    195 => ['name' => 'Ansem', 'type' => 'character'],
    196 => ['name' => 'Dr. Robotnik', 'type' => 'character'],
    197 => ['name' => 'Sin', 'type' => 'character'],
    198 => ['name' => 'Kuja', 'type' => 'character'],
    199 => ['name' => 'Master Hand', 'type' => 'character'],
    200 => ['name' => 'Joanna Dark', 'type' => 'character'],
    201 => ['name' => 'Carl Johnson', 'type' => 'character'],
    202 => ['name' => 'Lloyd Irving', 'type' => 'character'],
    203 => ['name' => 'Yuri', 'type' => 'character'],
    204 => ['name' => 'Riku', 'type' => 'character'],
    205 => ['name' => 'Big Boss', 'type' => 'character'],
    206 => ['name' => 'Manny Calavera', 'type' => 'character'],
    207 => ['name' => 'Kratos', 'type' => 'character'],
    208 => ['name' => 'Agent 47', 'type' => 'character'],
    209 => ['name' => 'Cecil Harvey', 'type' => 'character'],
    210 => ['name' => 'The King of All Cosmos', 'type' => 'character'],
    211 => ['name' => 'Chun-Li', 'type' => 'character'],
    212 => ['name' => 'Rikku', 'type' => 'character'],
    213 => ['name' => 'Zidane Tribal', 'type' => 'character'],
    214 => ['name' => 'Terra Branford', 'type' => 'character'],
    215 => ['name' => 'Sarah Kerrigan', 'type' => 'character'],
    216 => ['name' => 'Vincent Valentine', 'type' => 'character'],
    217 => ['name' => 'Geno', 'type' => 'character'],
    218 => ['name' => 'Jin Kazama', 'type' => 'character'],
    219 => ['name' => 'Kratos Aurion', 'type' => 'character'],
    220 => ['name' => 'Tifa Lockhart', 'type' => 'character'],
    221 => ['name' => 'Leon Kennedy', 'type' => 'character'],
    254 => ['name' => 'Nidoran F', 'type' => 'character'],
    255 => ['name' => 'Ada Wong', 'type' => 'character'],
    256 => ['name' => 'Jade', 'type' => 'character'],
    257 => ['name' => 'Lenneth Valkyrie', 'type' => 'character'],
    258 => ['name' => 'Kairi', 'type' => 'character'],
    259 => ['name' => 'Ivy Valentine', 'type' => 'character'],
    260 => ['name' => 'Celes Chere', 'type' => 'character'],
    261 => ['name' => 'The Boss', 'type' => 'character'],
    262 => ['name' => 'Sheena Fujibayashi', 'type' => 'character'],
    263 => ['name' => 'Princess Daisy', 'type' => 'character'],
    264 => ['name' => 'Princess Peach', 'type' => 'character'],
    265 => ['name' => 'Carmen Sandiego', 'type' => 'character'],
    266 => ['name' => 'Amy Rose', 'type' => 'character'],
    267 => ['name' => 'Marle', 'type' => 'character'],
    268 => ['name' => 'Roll', 'type' => 'character'],
    269 => ['name' => 'Cortana', 'type' => 'character'],
    270 => ['name' => 'Alyx Vance', 'type' => 'character'],
    271 => ['name' => 'Soma Cruz', 'type' => 'character'],
    272 => ['name' => 'Tingle', 'type' => 'character'],
    273 => ['name' => 'Phoenix Wright', 'type' => 'character'],
    274 => ['name' => 'Axel', 'type' => 'character'],
    275 => ['name' => 'Prince of Persia', 'type' => 'character'],
    276 => ['name' => 'Captain Falcon', 'type' => 'character'],
    277 => ['name' => 'Sub-Zero', 'type' => 'character'],
    278 => ['name' => 'Vaan', 'type' => 'character'],
    279 => ['name' => 'Arthas Menethil', 'type' => 'character'],
    280 => ['name' => 'Midna', 'type' => 'character'],
    281 => ['name' => 'Marcus Fenix', 'type' => 'character'],
    282 => ['name' => 'Zelos Wilder', 'type' => 'character'],
    283 => ['name' => 'Midgar Zolom', 'type' => 'character'],
    284 => ['name' => 'Chris Redfield', 'type' => 'character'],
    285 => ['name' => 'Mewtwo', 'type' => 'character'],
    286 => ['name' => 'Toad', 'type' => 'character'],
    287 => ['name' => 'Meta Knight', 'type' => 'character'],
    288 => ['name' => 'Banjo', 'type' => 'character'],
    289 => ['name' => 'Wander', 'type' => 'character'],
    290 => ['name' => 'Agent J', 'type' => 'character'],
    291 => ['name' => 'Bidoof', 'type' => 'character'],
    292 => ['name' => 'Miles Edgeworth', 'type' => 'character'],
    293 => ['name' => 'Mudkip', 'type' => 'character'],
    294 => ['name' => 'Pit', 'type' => 'character'],
    295 => ['name' => 'Thrall', 'type' => 'character'],
    296 => ['name' => 'Amaterasu', 'type' => 'character'],
    297 => ['name' => 'Matt', 'type' => 'character'],
    298 => ['name' => 'Balthier Bunansa', 'type' => 'character'],
    299 => ['name' => 'Frank West', 'type' => 'character'],
    300 => ['name' => 'Jade Curtiss', 'type' => 'character'],
    301 => ['name' => 'Serge', 'type' => 'character'],
    302 => ['name' => 'L-Block', 'type' => 'character'],
    303 => ['name' => 'Nathan Hale', 'type' => 'character'],
    304 => ['name' => 'Marth', 'type' => 'character'],
    305 => ['name' => 'Prince of All Cosmos', 'type' => 'character'],
    306 => ['name' => 'Nightmare', 'type' => 'character'],
    307 => ['name' => 'Rayman', 'type' => 'character'],
    308 => ['name' => 'Haseo', 'type' => 'character'],
    309 => ['name' => 'Roxas', 'type' => 'character'],
    310 => ['name' => 'Akuma', 'type' => 'character'],
    311 => ['name' => 'Daxter', 'type' => 'character'],
    312 => ['name' => 'Ike', 'type' => 'character'],
    313 => ['name' => '? Block', 'type' => 'character'],
    314 => ['name' => 'Paddle', 'type' => 'character'],
    315 => ['name' => 'Weighted Companion Cube', 'type' => 'character'],
    316 => ['name' => 'Zack Fair', 'type' => 'character'],
    317 => ['name' => 'Luke fon Fabre', 'type' => 'character'],
    318 => ['name' => 'Niko Bellic', 'type' => 'character'],
    319 => ['name' => 'Altair', 'type' => 'character'],
    320 => ['name' => 'Lucario', 'type' => 'character'],
    321 => ['name' => 'Sho Minamimoto', 'type' => 'character'],
    322 => ['name' => 'Deckard Cain', 'type' => 'character'],
    323 => ['name' => 'Fei Fong Wong', 'type' => 'character'],
    324 => ['name' => 'Mega Man X', 'type' => 'character'],
    325 => ['name' => 'Raz', 'type' => 'character'],
    326 => ['name' => 'Neku Sakuraba', 'type' => 'character'],
    327 => ['name' => 'Falco Lombardi', 'type' => 'character'],
    328 => ['name' => 'GlaDOS', 'type' => 'character'],
    329 => ['name' => 'Big Daddy', 'type' => 'character'],
    330 => ['name' => 'Kaim Argonar', 'type' => 'character'],
    331 => ['name' => 'The Dog', 'type' => 'character'],
    332 => ['name' => 'Diddy Kong', 'type' => 'character'],
    333 => ['name' => 'Spy', 'type' => 'character'],
    334 => ['name' => 'Nero', 'type' => 'character'],
    335 => ['name' => 'King Dedede', 'type' => 'character'],
    336 => ['name' => 'Sackboy', 'type' => 'character'],
    337 => ['name' => 'Tim', 'type' => 'character'],
    338 => ['name' => 'Nathan Drake', 'type' => 'character'],
    339 => ['name' => 'Axel Steel', 'type' => 'character'],
    340 => ['name' => 'Travis Touchdown', 'type' => 'character'],
    341 => ['name' => 'Jinjo', 'type' => 'character'],
    342 => ['name' => 'Lucas', 'type' => 'character'],
    343 => ['name' => 'Kain Highwind', 'type' => 'character'],
    344 => ['name' => 'Professor Layton', 'type' => 'character'],
    345 => ['name' => 'Captain MacMillan', 'type' => 'character'],
    346 => ['name' => 'Siegfried Schtauffen', 'type' => 'character'],
    347 => ['name' => 'Hogger', 'type' => 'character'],
    348 => ['name' => 'Commander Shepard', 'type' => 'character'],
    349 => ['name' => 'Sandbag', 'type' => 'character'],
    350 => ['name' => 'Rydia', 'type' => 'character'],
    351 => ['name' => 'Nana', 'type' => 'character'],
    352 => ['name' => 'Heavy', 'type' => 'character'],
    353 => ['name' => 'CD-I Link', 'type' => 'character'],
    354 => ['name' => 'Classic Link', 'type' => 'character'],
    355 => ['name' => 'Toon Link', 'type' => 'character'],
    356 => ['name' => 'Young Link', 'type' => 'character'],
    453 => ['name' => 'Pokemon Trainer Red', 'type' => 'character'],
    454 => ['name' => 'Captain John Price', 'type' => 'character'],
    455 => ['name' => 'Sandal', 'type' => 'character'],
    456 => ['name' => 'Lightning', 'type' => 'character'],
    457 => ['name' => 'Fawful', 'type' => 'character'],
    458 => ['name' => 'Claptrap', 'type' => 'character'],
    459 => ['name' => 'Prinny', 'type' => 'character'],
    460 => ['name' => 'Cid Highwind', 'type' => 'character'],
    461 => ['name' => 'Charizard', 'type' => 'character'],
    462 => ['name' => 'Jecht', 'type' => 'character'],
    463 => ['name' => 'Eddie Riggs', 'type' => 'character'],
    464 => ['name' => 'Ezio Auditore da Firenze', 'type' => 'character'],
    465 => ['name' => 'Vault Boy', 'type' => 'character'],
    466 => ['name' => 'Ellis', 'type' => 'character'],
    467 => ['name' => 'Darth Revan', 'type' => 'character'],
    468 => ['name' => 'Missingno', 'type' => 'character'],
    469 => ['name' => 'Soap MacTavish', 'type' => 'character'],
    470 => ['name' => 'Yuri Lowell', 'type' => 'character'],
    549 => ['name' => 'Santa Claus', 'type' => 'character'],
    614 => ['name' => 'Isaac (Binding)', 'type' => 'character'],
    615 => ['name' => 'Alan Wake', 'type' => 'character'],
    616 => ['name' => 'Waluigi', 'type' => 'character'],
    617 => ['name' => 'Demi-Fiend', 'type' => 'character'],
    618 => ['name' => 'Solaire of Astora', 'type' => 'character'],
    619 => ['name' => 'Juliet Starling', 'type' => 'character'],
    620 => ['name' => 'Tharja', 'type' => 'character'],
    621 => ['name' => 'Tiny Tina', 'type' => 'character'],
    622 => ['name' => 'Hero', 'type' => 'character'],
    623 => ['name' => 'Rinoa Heartilly', 'type' => 'character'],
    624 => ['name' => 'Chie Satonaka', 'type' => 'character'],
    625 => ['name' => 'Draven', 'type' => 'character'],
    626 => ['name' => 'Face McShooty', 'type' => 'character'],
    627 => ['name' => 'Jigglypuff', 'type' => 'character'],
    628 => ['name' => 'Welkin Gunther', 'type' => 'character'],
    629 => ['name' => 'Dan Hibiki', 'type' => 'character'],
    630 => ['name' => 'Caim', 'type' => 'character'],
    631 => ['name' => 'Dracula', 'type' => 'character'],
    632 => ['name' => 'Lucina', 'type' => 'character'],
    633 => ['name' => 'Barret Wallace', 'type' => 'character'],
    634 => ['name' => 'Reimu Hakurei', 'type' => 'character'],
    635 => ['name' => 'Dunban', 'type' => 'character'],
    636 => ['name' => 'Chester', 'type' => 'character'],
    637 => ['name' => 'Zero (999)', 'type' => 'character'],
    638 => ['name' => 'Chrom', 'type' => 'character'],
    639 => ['name' => 'Garrus Vakarian', 'type' => 'character'],
    640 => ['name' => 'Archer', 'type' => 'character'],
    641 => ['name' => 'Clementine', 'type' => 'character'],
    642 => ['name' => 'Reyn', 'type' => 'character'],
    643 => ['name' => 'Captain Viridian', 'type' => 'character'],
    644 => ['name' => 'Peacock', 'type' => 'character'],
    645 => ['name' => 'Locke Cole', 'type' => 'character'],
    646 => ['name' => 'Elizabeth', 'type' => 'character'],
    647 => ['name' => 'Poison', 'type' => 'character'],
    648 => ['name' => 'Wheatley', 'type' => 'character'],
    649 => ['name' => 'Commander Keen', 'type' => 'character'],
    650 => ['name' => 'Bayonetta', 'type' => 'character'],
    651 => ['name' => 'N', 'type' => 'character'],
    652 => ['name' => 'Cole', 'type' => 'character'],
    653 => ['name' => 'Ragna the Bloodedge', 'type' => 'character'],
    654 => ['name' => 'Epona', 'type' => 'character'],
    655 => ['name' => 'Mordin Solus', 'type' => 'character'],
    656 => ['name' => 'Shulk', 'type' => 'character'],
    657 => ['name' => 'Slime', 'type' => 'character'],
    658 => ['name' => 'Yuri Hyuga', 'type' => 'character'],
    659 => ['name' => 'Sen. Steven Armstrong', 'type' => 'character'],
    660 => ['name' => 'Handsome Jack', 'type' => 'character'],
    661 => ['name' => 'Francis York Morgan', 'type' => 'character'],
    662 => ['name' => 'Lugia', 'type' => 'character'],
    663 => ['name' => 'Squirtle', 'type' => 'character'],
    664 => ['name' => 'Spring Breeze Dancin\'', 'type' => 'character'],
    665 => ['name' => 'Kat', 'type' => 'character'],
    666 => ['name' => 'Yu Narukami', 'type' => 'character'],
    667 => ['name' => 'Oliver', 'type' => 'character'],
    668 => ['name' => 'Hades', 'type' => 'character'],
    669 => ['name' => 'Missile', 'type' => 'character'],
    670 => ['name' => 'Hal "Otacon" Emmerich', 'type' => 'character'],
    671 => ['name' => 'Booker DeWitt', 'type' => 'character'],
    672 => ['name' => 'Gilgamesh', 'type' => 'character'],
    673 => ['name' => 'Groose', 'type' => 'character'],
    674 => ['name' => 'Lu Bu', 'type' => 'character'],
    675 => ['name' => 'Yoshimitsu', 'type' => 'character'],
    676 => ['name' => 'Lee Everett', 'type' => 'character'],
    677 => ['name' => 'Meat Boy', 'type' => 'character'],
    678 => ['name' => 'Mr. Game & Watch', 'type' => 'character'],
    679 => ['name' => 'Steve', 'type' => 'character'],
    680 => ['name' => 'Pokemon Trainer Blue', 'type' => 'character'],
    681 => ['name' => 'Wolf O\'Donnell', 'type' => 'character'],
    682 => ['name' => 'Isaac Clarke', 'type' => 'character'],
    683 => ['name' => 'Catherine', 'type' => 'character'],
    684 => ['name' => 'Vaas Montenegro', 'type' => 'character'],
    685 => ['name' => 'Seifer Almasy', 'type' => 'character'],
    686 => ['name' => 'Palutena', 'type' => 'character'],
    687 => ['name' => 'Teemo', 'type' => 'character'],
    688 => ['name' => 'Dragonborn', 'type' => 'character'],
    689 => ['name' => 'Cirno', 'type' => 'character'],
    690 => ['name' => 'Adam Jensen', 'type' => 'character'],
    691 => ['name' => 'Marisa Kirisame', 'type' => 'character'],
    692 => ['name' => 'Commander Video', 'type' => 'character'],
    693 => ['name' => 'Adol Christin', 'type' => 'character'],
    694 => ['name' => 'Creeper', 'type' => 'character'],
    695 => ['name' => 'Corvo Attano', 'type' => 'character'],
    696 => ['name' => 'Sissel', 'type' => 'character'],
    697 => ['name' => 'Urdnot Wrex', 'type' => 'character'],
    698 => ['name' => 'Magikarp', 'type' => 'character'],
    699 => ['name' => 'Recette Lemongrass', 'type' => 'character'],
    700 => ['name' => 'Mike Haggar', 'type' => 'character'],
    701 => ['name' => 'Red Bird', 'type' => 'character'],
    702 => ['name' => 'Boko', 'type' => 'character'],
    703 => ['name' => 'Lyndis', 'type' => 'character'],
    704 => ['name' => 'John Marston', 'type' => 'character'],
    705 => ['name' => 'Nier', 'type' => 'character'],
    788 => ['name' => 'Cuphead', 'type' => 'character'],
    789 => ['name' => 'Chloe Price', 'type' => 'character'],
    790 => ['name' => 'Victor Sullivan', 'type' => 'character'],
    791 => ['name' => 'Primrose', 'type' => 'character'],
    792 => ['name' => 'Noctis Lucis Caelum', 'type' => 'character'],
    793 => ['name' => 'Monika', 'type' => 'character'],
    794 => ['name' => 'Shantae', 'type' => 'character'],
    795 => ['name' => 'James Sunderland', 'type' => 'character'],
    796 => ['name' => 'Velvet Crowe', 'type' => 'character'],
    797 => ['name' => 'Neptune', 'type' => 'character'],
    798 => ['name' => 'Godot', 'type' => 'character'],
    799 => ['name' => 'Kazuma Kiryu', 'type' => 'character'],
    800 => ['name' => '2B', 'type' => 'character'],
    801 => ['name' => 'Cayde-6', 'type' => 'character'],
    802 => ['name' => 'Joel', 'type' => 'character'],
    803 => ['name' => 'Estelle Bright', 'type' => 'character'],
    804 => ['name' => 'Guile', 'type' => 'character'],
    805 => ['name' => 'Hat Kid', 'type' => 'character'],
    806 => ['name' => 'Metal Sonic', 'type' => 'character'],
    807 => ['name' => 'Aloy', 'type' => 'character'],
    808 => ['name' => 'D.Va', 'type' => 'character'],
    809 => ['name' => 'Captain Toad', 'type' => 'character'],
    810 => ['name' => 'Shovel Knight', 'type' => 'character'],
    811 => ['name' => 'Geralt', 'type' => 'character'],
    812 => ['name' => 'Rosalina', 'type' => 'character'],
    813 => ['name' => 'Sans', 'type' => 'character'],
    814 => ['name' => 'Ren Amamiya / Joker', 'type' => 'character'],
    815 => ['name' => 'Monokuma', 'type' => 'character'],
    816 => ['name' => 'Goro Majima', 'type' => 'character'],
    817 => ['name' => 'Isabelle', 'type' => 'character'],
    818 => ['name' => 'Richter Belmont', 'type' => 'character'],
    819 => ['name' => 'Metal Man', 'type' => 'character'],
    820 => ['name' => 'King K. Rool', 'type' => 'character'],
    821 => ['name' => 'Ellie', 'type' => 'character'],
    822 => ['name' => 'Aqua', 'type' => 'character'],
    823 => ['name' => 'Quiet', 'type' => 'character'],

    /* ---- game (379): ids 95-917 ---- */
    95  => ['name' => 'Metal Gear', 'type' => 'game'],
    96  => ['name' => 'Super Mario Bros. 3', 'type' => 'game'],
    97  => ['name' => 'Metroid', 'type' => 'game'],
    98  => ['name' => 'Pac-Man', 'type' => 'game'],
    99  => ['name' => 'Contra', 'type' => 'game'],
    100 => ['name' => 'Phantasy Star', 'type' => 'game'],
    101 => ['name' => 'Final Fantasy', 'type' => 'game'],
    102 => ['name' => 'Pitfall', 'type' => 'game'],
    103 => ['name' => 'Donkey Kong', 'type' => 'game'],
    104 => ['name' => 'Duck Hunt', 'type' => 'game'],
    105 => ['name' => 'Adventure', 'type' => 'game'],
    106 => ['name' => 'The Legend of Zelda', 'type' => 'game'],
    107 => ['name' => 'Pong', 'type' => 'game'],
    108 => ['name' => 'River City Ransom', 'type' => 'game'],
    109 => ['name' => 'Galaga', 'type' => 'game'],
    110 => ['name' => 'Tetris', 'type' => 'game'],
    111 => ['name' => 'Chrono Trigger', 'type' => 'game'],
    112 => ['name' => 'Secret of Mana', 'type' => 'game'],
    113 => ['name' => 'Street Fighter II', 'type' => 'game'],
    114 => ['name' => 'Super Mario RPG', 'type' => 'game'],
    115 => ['name' => 'Shining Force', 'type' => 'game'],
    116 => ['name' => 'Sonic 2', 'type' => 'game'],
    117 => ['name' => 'Super Mario World', 'type' => 'game'],
    118 => ['name' => 'The Simpsons', 'type' => 'game'],
    119 => ['name' => 'A Link to the Past', 'type' => 'game'],
    120 => ['name' => 'Gunstar Heroes', 'type' => 'game'],
    121 => ['name' => 'Phantasy Star IV', 'type' => 'game'],
    122 => ['name' => 'Super Metroid', 'type' => 'game'],
    123 => ['name' => 'Doom', 'type' => 'game'],
    124 => ['name' => 'EarthBound', 'type' => 'game'],
    125 => ['name' => 'Final Fantasy VI', 'type' => 'game'],
    126 => ['name' => 'Mortal Kombat', 'type' => 'game'],
    127 => ['name' => 'Final Fantasy VII', 'type' => 'game'],
    128 => ['name' => 'Suikoden II', 'type' => 'game'],
    129 => ['name' => 'Pokemon Gold/Silver/Crystal', 'type' => 'game'],
    130 => ['name' => 'Xenogears', 'type' => 'game'],
    131 => ['name' => 'Dance Dance Revolution', 'type' => 'game'],
    132 => ['name' => 'Final Fantasy Tactics', 'type' => 'game'],
    133 => ['name' => 'Metal Gear Solid', 'type' => 'game'],
    134 => ['name' => 'Resident Evil', 'type' => 'game'],
    135 => ['name' => 'Perfect Dark', 'type' => 'game'],
    136 => ['name' => 'Symphony of the Night', 'type' => 'game'],
    137 => ['name' => 'Goldeneye', 'type' => 'game'],
    138 => ['name' => 'Panzer Dragoon Saga', 'type' => 'game'],
    139 => ['name' => 'NiGHTS into dreams...', 'type' => 'game'],
    140 => ['name' => 'Super Mario 64', 'type' => 'game'],
    141 => ['name' => 'Fallout 2', 'type' => 'game'],
    142 => ['name' => 'Ocarina of Time', 'type' => 'game'],
    143 => ['name' => 'Halo', 'type' => 'game'],
    144 => ['name' => 'Starcraft', 'type' => 'game'],
    145 => ['name' => 'Kingdom Hearts', 'type' => 'game'],
    146 => ['name' => 'Soul Calibur', 'type' => 'game'],
    147 => ['name' => 'Skies of Arcadia', 'type' => 'game'],
    148 => ['name' => 'The Wind Waker', 'type' => 'game'],
    149 => ['name' => 'Half-Life', 'type' => 'game'],
    150 => ['name' => 'Metroid Prime', 'type' => 'game'],
    151 => ['name' => 'Final Fantasy Tactics Advance', 'type' => 'game'],
    152 => ['name' => 'Fire Emblem', 'type' => 'game'],
    153 => ['name' => 'Final Fantasy X', 'type' => 'game'],
    154 => ['name' => 'Shenmue', 'type' => 'game'],
    155 => ['name' => 'Knights of the Old Republic', 'type' => 'game'],
    156 => ['name' => 'Vice City', 'type' => 'game'],
    157 => ['name' => 'Metal Gear Solid 2', 'type' => 'game'],
    158 => ['name' => 'Super Smash Bros. Melee', 'type' => 'game'],
    159 => ['name' => 'Wind Waker', 'type' => 'game'],
    357 => ['name' => 'Mike Tyson\'s Punch-Out!!', 'type' => 'game'],
    358 => ['name' => 'Space Invaders', 'type' => 'game'],
    359 => ['name' => 'Mega Man 2', 'type' => 'game'],
    360 => ['name' => 'The Oregon Trail', 'type' => 'game'],
    361 => ['name' => 'Ninja Gaiden', 'type' => 'game'],
    362 => ['name' => 'Super Mario Bros.', 'type' => 'game'],
    363 => ['name' => 'Dragon Warrior III', 'type' => 'game'],
    364 => ['name' => 'Castlevania III', 'type' => 'game'],
    365 => ['name' => 'Civilization', 'type' => 'game'],
    366 => ['name' => 'Sonic the Hedgehog', 'type' => 'game'],
    367 => ['name' => 'Secret of Monkey Island', 'type' => 'game'],
    368 => ['name' => 'SimCity', 'type' => 'game'],
    369 => ['name' => 'Tecmo Super Bowl', 'type' => 'game'],
    370 => ['name' => 'Battletoads', 'type' => 'game'],
    371 => ['name' => 'Prince of Persia', 'type' => 'game'],
    372 => ['name' => 'Crystalis', 'type' => 'game'],
    373 => ['name' => 'Final Fantasy II (IV)', 'type' => 'game'],
    374 => ['name' => 'Mega Man 3', 'type' => 'game'],
    375 => ['name' => 'Sonic the Hedgehog 3', 'type' => 'game'],
    376 => ['name' => 'Super Mario Kart', 'type' => 'game'],
    377 => ['name' => 'Donkey Kong Country', 'type' => 'game'],
    378 => ['name' => 'Streets of Rage II', 'type' => 'game'],
    379 => ['name' => 'Zelda: A Link to the Past', 'type' => 'game'],
    380 => ['name' => 'Final Fantasy III (VI)', 'type' => 'game'],
    381 => ['name' => 'Mega Man X', 'type' => 'game'],
    382 => ['name' => 'Zelda: Link\'s Awakening', 'type' => 'game'],
    383 => ['name' => 'Mortal Kombat II', 'type' => 'game'],
    384 => ['name' => 'Shining Force II', 'type' => 'game'],
    385 => ['name' => 'Sonic the Hedgehog 2', 'type' => 'game'],
    386 => ['name' => 'Donkey Kong Country 2', 'type' => 'game'],
    387 => ['name' => 'GoldenEye 007', 'type' => 'game'],
    388 => ['name' => 'Resident Evil 2', 'type' => 'game'],
    389 => ['name' => 'Mario Kart 64', 'type' => 'game'],
    390 => ['name' => 'Star Fox 64', 'type' => 'game'],
    391 => ['name' => 'Suikoden', 'type' => 'game'],
    392 => ['name' => 'Castlevania: Symphony of the Night', 'type' => 'game'],
    393 => ['name' => 'Kirby Super Star', 'type' => 'game'],
    394 => ['name' => 'Lufia II', 'type' => 'game'],
    395 => ['name' => 'Super Mario World 2: Yoshi\'s Island', 'type' => 'game'],
    396 => ['name' => 'Banjo-Kazooie', 'type' => 'game'],
    397 => ['name' => 'Pokemon Red/Blue/Yellow', 'type' => 'game'],
    398 => ['name' => 'The Legend of Zelda: Majora\'s Mask', 'type' => 'game'],
    399 => ['name' => 'Deus Ex', 'type' => 'game'],
    400 => ['name' => 'Pokemon Gold/Silver', 'type' => 'game'],
    401 => ['name' => 'Final Fantasy VIII', 'type' => 'game'],
    402 => ['name' => 'SoulCalibur', 'type' => 'game'],
    403 => ['name' => 'Chrono Cross', 'type' => 'game'],
    404 => ['name' => 'Final Fantasy IX', 'type' => 'game'],
    405 => ['name' => 'The Legend of Zelda: Ocarina of Time', 'type' => 'game'],
    406 => ['name' => 'Silent Hill 2', 'type' => 'game'],
    407 => ['name' => 'The Elder Scrolls III: Morrowind', 'type' => 'game'],
    408 => ['name' => 'Grand Theft Auto: Vice City', 'type' => 'game'],
    409 => ['name' => 'Paper Mario', 'type' => 'game'],
    410 => ['name' => 'Diablo II: Lord of Destruction', 'type' => 'game'],
    411 => ['name' => 'Grand Theft Auto III', 'type' => 'game'],
    412 => ['name' => 'Halo: Combat Evolved', 'type' => 'game'],
    413 => ['name' => 'Star Wars: Knights of the Old Republic', 'type' => 'game'],
    414 => ['name' => 'Disgaea: Hour of Darkness', 'type' => 'game'],
    415 => ['name' => 'The Legend of Zelda: The Wind Waker', 'type' => 'game'],
    416 => ['name' => 'God of War', 'type' => 'game'],
    417 => ['name' => 'Grand Theft Auto: San Andreas', 'type' => 'game'],
    418 => ['name' => 'Tales of Symphonia', 'type' => 'game'],
    419 => ['name' => 'The Elder Scrolls IV: Oblivion', 'type' => 'game'],
    420 => ['name' => 'Halo 2', 'type' => 'game'],
    421 => ['name' => 'Metal Gear Solid 3', 'type' => 'game'],
    422 => ['name' => 'Okami', 'type' => 'game'],
    423 => ['name' => 'World of Warcraft', 'type' => 'game'],
    424 => ['name' => 'Gears of War', 'type' => 'game'],
    425 => ['name' => 'Kingdom Hearts II', 'type' => 'game'],
    426 => ['name' => 'Resident Evil 4', 'type' => 'game'],
    427 => ['name' => 'Shadow of the Colossus', 'type' => 'game'],
    428 => ['name' => 'Final Fantasy XII', 'type' => 'game'],
    429 => ['name' => 'Half-Life 2', 'type' => 'game'],
    430 => ['name' => 'Phoenix Wright: Ace Attorney', 'type' => 'game'],
    431 => ['name' => 'The Legend of Zelda: Twilight Princess', 'type' => 'game'],
    432 => ['name' => 'Grand Theft Auto IV', 'type' => 'game'],
    433 => ['name' => 'Persona 4', 'type' => 'game'],
    434 => ['name' => 'Street Fighter IV', 'type' => 'game'],
    435 => ['name' => 'Super Smash Bros. Brawl', 'type' => 'game'],
    436 => ['name' => 'Call of Duty 4', 'type' => 'game'],
    437 => ['name' => 'Pokemon Diamond/Pearl', 'type' => 'game'],
    438 => ['name' => 'Super Mario Galaxy', 'type' => 'game'],
    439 => ['name' => 'Team Fortress 2', 'type' => 'game'],
    440 => ['name' => 'BioShock', 'type' => 'game'],
    441 => ['name' => 'LittleBigPlanet', 'type' => 'game'],
    442 => ['name' => 'Metal Gear Solid 4', 'type' => 'game'],
    443 => ['name' => 'Portal', 'type' => 'game'],
    444 => ['name' => 'Fallout 3', 'type' => 'game'],
    445 => ['name' => 'Halo 3', 'type' => 'game'],
    446 => ['name' => 'Left 4 Dead', 'type' => 'game'],
    447 => ['name' => 'Mass Effect', 'type' => 'game'],
    448 => ['name' => 'The Secret of Monkey Island', 'type' => 'game'],
    449 => ['name' => 'The Legend of Zelda: A Link to the Past', 'type' => 'game'],
    450 => ['name' => 'The Legend of Zelda: Link\'s Awakening', 'type' => 'game'],
    451 => ['name' => 'The Legend of Zelda: Wind Waker', 'type' => 'game'],
    452 => ['name' => 'Zelda: Twilight Princess', 'type' => 'game'],
    471 => ['name' => 'inFamous', 'type' => 'game'],
    472 => ['name' => 'Rock Band 2', 'type' => 'game'],
    473 => ['name' => 'Batman: Arkham Asylum', 'type' => 'game'],
    474 => ['name' => 'Psychonauts', 'type' => 'game'],
    475 => ['name' => 'Fable', 'type' => 'game'],
    476 => ['name' => 'The Legend of Dragoon', 'type' => 'game'],
    477 => ['name' => 'Uncharted 2: Among Thieves', 'type' => 'game'],
    478 => ['name' => 'Sonic Adventure 2', 'type' => 'game'],
    479 => ['name' => 'Super Mario Sunshine', 'type' => 'game'],
    480 => ['name' => 'Star Ocean: Till the End of Time', 'type' => 'game'],
    481 => ['name' => 'Devil May Cry 3: Dante\'s Awakening', 'type' => 'game'],
    482 => ['name' => 'Mother 3', 'type' => 'game'],
    483 => ['name' => 'Demon\'s Souls', 'type' => 'game'],
    484 => ['name' => 'Mega Man 9', 'type' => 'game'],
    485 => ['name' => 'No More Heroes', 'type' => 'game'],
    486 => ['name' => 'Resident Evil 5', 'type' => 'game'],
    487 => ['name' => 'Left 4 Dead 2', 'type' => 'game'],
    488 => ['name' => 'Guitar Hero II', 'type' => 'game'],
    489 => ['name' => 'Warcraft III: Reign of Chaos', 'type' => 'game'],
    490 => ['name' => 'Conker\'s Bad Fur Day', 'type' => 'game'],
    491 => ['name' => 'Call of Duty 4: Modern Warfare', 'type' => 'game'],
    492 => ['name' => 'Prince of Persia: The Sands of Time', 'type' => 'game'],
    493 => ['name' => 'Metroid Fusion', 'type' => 'game'],
    494 => ['name' => 'Pokemon Diamond/Pearl/Platinum', 'type' => 'game'],
    495 => ['name' => 'Fire Emblem: Path of Radiance', 'type' => 'game'],
    496 => ['name' => 'WWF No Mercy', 'type' => 'game'],
    497 => ['name' => 'Valkyria Chronicles', 'type' => 'game'],
    498 => ['name' => 'Mario Kart DS', 'type' => 'game'],
    499 => ['name' => 'Beyond Good & Evil', 'type' => 'game'],
    500 => ['name' => 'Pokemon Ruby/Sapphire/Emerald', 'type' => 'game'],
    501 => ['name' => 'Dragon Age: Origins', 'type' => 'game'],
    502 => ['name' => 'F-Zero GX', 'type' => 'game'],
    503 => ['name' => 'Star Wars: Battlefront II', 'type' => 'game'],
    504 => ['name' => 'Call of Duty: Modern Warfare 2', 'type' => 'game'],
    505 => ['name' => 'Dissidia: Final Fantasy', 'type' => 'game'],
    506 => ['name' => 'Castlevania: Dawn of Sorrow', 'type' => 'game'],
    507 => ['name' => 'Viewtiful Joe', 'type' => 'game'],
    508 => ['name' => 'Borderlands', 'type' => 'game'],
    509 => ['name' => 'Tales of Vesperia', 'type' => 'game'],
    510 => ['name' => 'Golden Sun', 'type' => 'game'],
    511 => ['name' => 'Ratchet & Clank: Up Your Arsenal', 'type' => 'game'],
    512 => ['name' => 'Dead Space', 'type' => 'game'],
    513 => ['name' => 'Devil May Cry', 'type' => 'game'],
    514 => ['name' => 'Tony Hawk\'s Pro Skater 2', 'type' => 'game'],
    515 => ['name' => 'Civilization IV', 'type' => 'game'],
    516 => ['name' => 'Shin Megami Tensei: Persona 3', 'type' => 'game'],
    517 => ['name' => 'Phoenix Wright: Ace Attorney Trials and Tribulatio', 'type' => 'game'],
    518 => ['name' => 'Jet Grind Radio', 'type' => 'game'],
    519 => ['name' => 'Dead Rising', 'type' => 'game'],
    520 => ['name' => 'The World Ends With You', 'type' => 'game'],
    521 => ['name' => 'Braid', 'type' => 'game'],
    522 => ['name' => 'Shin Megami Tensei: Persona 4', 'type' => 'game'],
    523 => ['name' => 'Gears of War 2', 'type' => 'game'],
    524 => ['name' => 'Crisis Core: Final Fantasy VII', 'type' => 'game'],
    525 => ['name' => 'Baldur\'s Gate II: Shadows of Amn', 'type' => 'game'],
    526 => ['name' => 'Plants vs. Zombies', 'type' => 'game'],
    527 => ['name' => 'Metal Gear Solid 3: Snake Eater', 'type' => 'game'],
    528 => ['name' => 'TimeSplitters 2', 'type' => 'game'],
    529 => ['name' => 'Marvel vs. Capcom 2', 'type' => 'game'],
    530 => ['name' => 'New Super Mario Bros. Wii', 'type' => 'game'],
    531 => ['name' => 'Katamari Damacy', 'type' => 'game'],
    532 => ['name' => 'Animal Crossing', 'type' => 'game'],
    533 => ['name' => 'Assassin\'s Creed', 'type' => 'game'],
    534 => ['name' => 'Metal Gear Solid 4: Guns of the Patriots', 'type' => 'game'],
    535 => ['name' => 'Diablo II', 'type' => 'game'],
    536 => ['name' => 'Eternal Darkness: Sanity\'s Requiem', 'type' => 'game'],
    537 => ['name' => 'Banjo-Tooie', 'type' => 'game'],
    538 => ['name' => 'Metal Gear Solid 2: Sons of Liberty', 'type' => 'game'],
    539 => ['name' => 'The Sims', 'type' => 'game'],
    540 => ['name' => 'Wii Sports', 'type' => 'game'],
    541 => ['name' => 'Dragon Quest VIII: Journey of the Cursed King', 'type' => 'game'],
    542 => ['name' => 'Mario Kart Wii', 'type' => 'game'],
    543 => ['name' => 'Advance Wars', 'type' => 'game'],
    544 => ['name' => 'God of War II', 'type' => 'game'],
    545 => ['name' => 'Assassin\'s Creed II', 'type' => 'game'],
    546 => ['name' => 'ICO', 'type' => 'game'],
    547 => ['name' => 'Paper Mario: The Thousand-Year Door', 'type' => 'game'],
    548 => ['name' => 'SoulCalibur II', 'type' => 'game'],
    706 => ['name' => 'Batman: Arkham City', 'type' => 'game'],
    707 => ['name' => 'Pokemon Gold/Silver/Crystal Version', 'type' => 'game'],
    708 => ['name' => 'The Last of Us', 'type' => 'game'],
    709 => ['name' => 'Pokemon X/Y', 'type' => 'game'],
    710 => ['name' => 'Planescape: Torment', 'type' => 'game'],
    711 => ['name' => 'Super Smash Bros. for Wii U', 'type' => 'game'],
    712 => ['name' => 'Super Mario Galaxy 2', 'type' => 'game'],
    713 => ['name' => 'Minecraft', 'type' => 'game'],
    714 => ['name' => 'Journey', 'type' => 'game'],
    715 => ['name' => 'Age of Empires II: The Age of Kings', 'type' => 'game'],
    716 => ['name' => 'Pokemon Red/Blue/Yellow/Green Version', 'type' => 'game'],
    717 => ['name' => 'Portal 2', 'type' => 'game'],
    718 => ['name' => 'The Walking Dead: A Telltale Games Series', 'type' => 'game'],
    719 => ['name' => 'Life is Strange', 'type' => 'game'],
    720 => ['name' => 'Mass Effect 3', 'type' => 'game'],
    721 => ['name' => 'Undertale', 'type' => 'game'],
    722 => ['name' => 'Animal Crossing: New Leaf', 'type' => 'game'],
    723 => ['name' => 'The Elder Scrolls V: Skyrim', 'type' => 'game'],
    724 => ['name' => 'Mario Kart 8', 'type' => 'game'],
    725 => ['name' => 'Nine Hours, Nine Persons, Nine Doors', 'type' => 'game'],
    726 => ['name' => 'Hearthstone: Heroes of Warcraft', 'type' => 'game'],
    727 => ['name' => 'Monster Hunter 4 Ultimate', 'type' => 'game'],
    728 => ['name' => 'Donkey Kong Country 2: Diddy\'s Kong Quest', 'type' => 'game'],
    729 => ['name' => 'Xenoblade Chronicles', 'type' => 'game'],
    730 => ['name' => 'Fire Emblem: Awakening', 'type' => 'game'],
    731 => ['name' => 'Super Mario Maker', 'type' => 'game'],
    732 => ['name' => 'Cave Story', 'type' => 'game'],
    733 => ['name' => 'Final Fantasy IV', 'type' => 'game'],
    734 => ['name' => 'Metal Gear Solid V: The Phantom Pain', 'type' => 'game'],
    735 => ['name' => 'Dark Souls', 'type' => 'game'],
    736 => ['name' => 'Sid Meier\'s Civilization V', 'type' => 'game'],
    737 => ['name' => 'Bloodborne', 'type' => 'game'],
    738 => ['name' => 'Grand Theft Auto V', 'type' => 'game'],
    739 => ['name' => 'Super Mario RPG: Legend of the Seven Stars', 'type' => 'game'],
    740 => ['name' => 'Shovel Knight', 'type' => 'game'],
    741 => ['name' => 'The Binding of Isaac: Rebirth', 'type' => 'game'],
    742 => ['name' => 'The Witcher 3: Wild Hunt', 'type' => 'game'],
    743 => ['name' => 'BioShock Infinite', 'type' => 'game'],
    744 => ['name' => 'Fallout: New Vegas', 'type' => 'game'],
    745 => ['name' => 'Splatoon', 'type' => 'game'],
    746 => ['name' => 'Borderlands 2', 'type' => 'game'],
    747 => ['name' => 'Bayonetta 2', 'type' => 'game'],
    748 => ['name' => 'Red Dead Redemption', 'type' => 'game'],
    749 => ['name' => 'Destiny', 'type' => 'game'],
    750 => ['name' => 'Mass Effect 2', 'type' => 'game'],
    751 => ['name' => 'Zero Escape: Virtue\'s Last Reward', 'type' => 'game'],
    824 => ['name' => 'The Legend of Zelda: Breath of the Wild', 'type' => 'game'],
    825 => ['name' => 'The Outer Worlds', 'type' => 'game'],
    826 => ['name' => 'Halo: Reach', 'type' => 'game'],
    827 => ['name' => 'Final Fantasy XV', 'type' => 'game'],
    828 => ['name' => 'What Remains of Edith Finch', 'type' => 'game'],
    829 => ['name' => 'Hollow Knight', 'type' => 'game'],
    830 => ['name' => 'Tales of Berseria', 'type' => 'game'],
    831 => ['name' => 'Bravely Default: Flying Fairy', 'type' => 'game'],
    832 => ['name' => 'Monster Hunter: World', 'type' => 'game'],
    833 => ['name' => 'Ni no Kuni: Wrath of the White Witch', 'type' => 'game'],
    834 => ['name' => 'Sekiro: Shadows Die Twice', 'type' => 'game'],
    835 => ['name' => 'Bastion', 'type' => 'game'],
    836 => ['name' => 'Dragon Quest XI: Echoes of an Elusive Age', 'type' => 'game'],
    837 => ['name' => 'The Legend of Heroes: Trails in the Sky SC', 'type' => 'game'],
    838 => ['name' => 'Resident Evil 7: biohazard', 'type' => 'game'],
    839 => ['name' => 'Fallout 4', 'type' => 'game'],
    840 => ['name' => 'VVVVVV', 'type' => 'game'],
    841 => ['name' => 'Bloodstained: Ritual of the Night', 'type' => 'game'],
    842 => ['name' => 'Fortnite', 'type' => 'game'],
    843 => ['name' => 'Horizon Zero Dawn', 'type' => 'game'],
    844 => ['name' => 'Danganronpa 2: Goodbye Despair', 'type' => 'game'],
    845 => ['name' => 'DOOM', 'type' => 'game'],
    846 => ['name' => 'INSIDE', 'type' => 'game'],
    847 => ['name' => 'Deus Ex: Human Revolution', 'type' => 'game'],
    848 => ['name' => 'Call of Duty: Black Ops', 'type' => 'game'],
    849 => ['name' => 'Super Smash Bros. Ultimate', 'type' => 'game'],
    850 => ['name' => 'Tekken 7', 'type' => 'game'],
    851 => ['name' => 'Bayonetta', 'type' => 'game'],
    852 => ['name' => 'The Legend of Zelda: A Link Between Worlds', 'type' => 'game'],
    853 => ['name' => 'Dead Space 2', 'type' => 'game'],
    854 => ['name' => 'Marvel\'s Spider-Man', 'type' => 'game'],
    855 => ['name' => 'Dota 2', 'type' => 'game'],
    856 => ['name' => 'Octopath Traveler', 'type' => 'game'],
    857 => ['name' => 'Dragon\'s Dogma', 'type' => 'game'],
    858 => ['name' => 'Devil May Cry 5', 'type' => 'game'],
    859 => ['name' => 'Donkey Kong Country: Tropical Freeze', 'type' => 'game'],
    860 => ['name' => 'Mortal Kombat 11', 'type' => 'game'],
    861 => ['name' => 'Super Mario Odyssey', 'type' => 'game'],
    862 => ['name' => 'Baba Is You', 'type' => 'game'],
    863 => ['name' => 'Cuphead', 'type' => 'game'],
    864 => ['name' => 'XCOM 2', 'type' => 'game'],
    865 => ['name' => 'FTL: Faster Than Light', 'type' => 'game'],
    866 => ['name' => 'Persona 4 Golden', 'type' => 'game'],
    867 => ['name' => 'Ghost Trick: Phantom Detective', 'type' => 'game'],
    868 => ['name' => 'Splatoon 2', 'type' => 'game'],
    869 => ['name' => 'Death Stranding', 'type' => 'game'],
    870 => ['name' => 'Overwatch', 'type' => 'game'],
    871 => ['name' => 'Dragon Age: Inquisition', 'type' => 'game'],
    872 => ['name' => 'Ori and the Blind Forest', 'type' => 'game'],
    873 => ['name' => 'Fire Emblem: Three Houses', 'type' => 'game'],
    874 => ['name' => 'South Park: The Stick of Truth', 'type' => 'game'],
    875 => ['name' => 'Assassin\'s Creed Odyssey', 'type' => 'game'],
    876 => ['name' => 'Starcraft II: Wings of Liberty', 'type' => 'game'],
    877 => ['name' => 'Stardew Valley', 'type' => 'game'],
    878 => ['name' => 'Return of the Obra Dinn', 'type' => 'game'],
    879 => ['name' => 'The Stanley Parable', 'type' => 'game'],
    880 => ['name' => 'Dark Souls III', 'type' => 'game'],
    881 => ['name' => 'Dishonored', 'type' => 'game'],
    882 => ['name' => 'Nioh', 'type' => 'game'],
    883 => ['name' => 'The Talos Principle', 'type' => 'game'],
    884 => ['name' => 'Heavy Rain', 'type' => 'game'],
    885 => ['name' => 'Persona 5', 'type' => 'game'],
    886 => ['name' => 'Assassin\'s Creed IV: Black Flag', 'type' => 'game'],
    887 => ['name' => 'Sonic Mania', 'type' => 'game'],
    888 => ['name' => 'Ys VIII: Lacrimosa of DANA', 'type' => 'game'],
    889 => ['name' => 'Slay the Spire', 'type' => 'game'],
    890 => ['name' => 'Super Meat Boy', 'type' => 'game'],
    891 => ['name' => 'Tomb Raider', 'type' => 'game'],
    892 => ['name' => 'Disco Elysium', 'type' => 'game'],
    893 => ['name' => 'Kingdom Hearts III', 'type' => 'game'],
    894 => ['name' => 'Street Fighter V', 'type' => 'game'],
    895 => ['name' => 'Dying Light', 'type' => 'game'],
    896 => ['name' => 'Red Dead Redemption 2', 'type' => 'game'],
    897 => ['name' => 'Hotline Miami', 'type' => 'game'],
    898 => ['name' => 'Dragon Ball FighterZ', 'type' => 'game'],
    899 => ['name' => 'Rocket League', 'type' => 'game'],
    900 => ['name' => 'The Witness', 'type' => 'game'],
    901 => ['name' => 'Yakuza 0', 'type' => 'game'],
    902 => ['name' => 'Dead Cells', 'type' => 'game'],
    903 => ['name' => 'Xenoblade Chronicles 2', 'type' => 'game'],
    904 => ['name' => 'Terraria', 'type' => 'game'],
    905 => ['name' => 'Diablo III', 'type' => 'game'],
    906 => ['name' => 'Crusader Kings II', 'type' => 'game'],
    907 => ['name' => 'Subnautica', 'type' => 'game'],
    908 => ['name' => 'Fate / Grand Order', 'type' => 'game'],
    909 => ['name' => 'Crypt of the NecroDancer', 'type' => 'game'],
    910 => ['name' => 'Final Fantasy XIV Online: A Realm Reborn', 'type' => 'game'],
    911 => ['name' => 'Uncharted 4: A Thief\'s End', 'type' => 'game'],
    912 => ['name' => 'Night in the Woods', 'type' => 'game'],
    913 => ['name' => 'Pokemon HeartGold / SoulSilver Version', 'type' => 'game'],
    914 => ['name' => 'Celeste', 'type' => 'game'],
    915 => ['name' => 'Rayman Legends', 'type' => 'game'],
    916 => ['name' => 'Divinity: Original Sin II', 'type' => 'game'],
    917 => ['name' => 'NieR: Automata', 'type' => 'game'],

    /* ---- series (32): ids 222-253 ---- */
    222 => ['name' => 'Civilization', 'type' => 'series'],
    223 => ['name' => 'The Legend of Zelda', 'type' => 'series'],
    224 => ['name' => 'Mega Man X', 'type' => 'series'],
    225 => ['name' => 'Suikoden', 'type' => 'series'],
    226 => ['name' => 'Pokemon', 'type' => 'series'],
    227 => ['name' => 'Star Ocean', 'type' => 'series'],
    228 => ['name' => 'Kirby', 'type' => 'series'],
    229 => ['name' => 'Metroid', 'type' => 'series'],
    230 => ['name' => 'Metal Gear', 'type' => 'series'],
    231 => ['name' => 'Soul Calibur', 'type' => 'series'],
    232 => ['name' => 'Fire Emblem', 'type' => 'series'],
    233 => ['name' => 'Silent Hill', 'type' => 'series'],
    234 => ['name' => 'Castlevania', 'type' => 'series'],
    235 => ['name' => 'Halo', 'type' => 'series'],
    236 => ['name' => 'Harvest Moon', 'type' => 'series'],
    237 => ['name' => 'Kingdom Hearts', 'type' => 'series'],
    238 => ['name' => 'Madden NFL', 'type' => 'series'],
    239 => ['name' => 'Super Mario Bros.', 'type' => 'series'],
    240 => ['name' => 'Grand Theft Auto', 'type' => 'series'],
    241 => ['name' => 'Warcraft', 'type' => 'series'],
    242 => ['name' => 'Devil May Cry', 'type' => 'series'],
    243 => ['name' => 'Sonic the Hedgehog', 'type' => 'series'],
    244 => ['name' => 'Dragon Quest', 'type' => 'series'],
    245 => ['name' => 'Super Smash Bros.', 'type' => 'series'],
    246 => ['name' => 'Diablo', 'type' => 'series'],
    247 => ['name' => 'Final Fantasy', 'type' => 'series'],
    248 => ['name' => 'Mario Kart', 'type' => 'series'],
    249 => ['name' => 'Mega Man', 'type' => 'series'],
    250 => ['name' => 'Street Fighter', 'type' => 'series'],
    251 => ['name' => 'The Elder Scrolls', 'type' => 'series'],
    252 => ['name' => 'Resident Evil', 'type' => 'series'],
    253 => ['name' => 'Shadow Hearts', 'type' => 'series'],

    /* ---- rivalry (64): ids 550-613 ---- */
    550 => ['name' => 'Earthworm Jim vs. Queen Slug-for-a-Butt', 'type' => 'rivalry'],
    551 => ['name' => 'Mario vs. Bowser', 'type' => 'rivalry'],
    552 => ['name' => 'Conker vs. The Great Mighty Poo', 'type' => 'rivalry'],
    553 => ['name' => 'Ike vs. Black Knight', 'type' => 'rivalry'],
    554 => ['name' => 'Jill Valentine vs. Nemesis', 'type' => 'rivalry'],
    555 => ['name' => 'Kirby vs. Meta Knight', 'type' => 'rivalry'],
    556 => ['name' => 'Katherine vs. Catherine', 'type' => 'rivalry'],
    557 => ['name' => 'Sonic the Hedgehog vs. Dr. Robotnik', 'type' => 'rivalry'],
    558 => ['name' => 'Captain Falcon vs. Black Shadow', 'type' => 'rivalry'],
    559 => ['name' => 'Mega Man X vs. Zero', 'type' => 'rivalry'],
    560 => ['name' => 'Bartz Klauser vs. Gilgamesh', 'type' => 'rivalry'],
    561 => ['name' => 'Guybrush Threepwood vs. LeChuck', 'type' => 'rivalry'],
    562 => ['name' => 'Donkey Kong vs. King K. Rool', 'type' => 'rivalry'],
    563 => ['name' => 'Ezio Auditore da Firenze vs. Rodrigo Borgia', 'type' => 'rivalry'],
    564 => ['name' => 'Leon Kennedy vs. Ada Wong', 'type' => 'rivalry'],
    565 => ['name' => 'Sub-Zero vs. Scorpion', 'type' => 'rivalry'],
    566 => ['name' => 'Jim Raynor vs. Sarah Kerrigan', 'type' => 'rivalry'],
    567 => ['name' => 'Pokemon Trainer Red vs. Pokemon Trainer Blue', 'type' => 'rivalry'],
    568 => ['name' => 'Cecil Harvey vs. Golbez', 'type' => 'rivalry'],
    569 => ['name' => 'Luigi vs. Waluigi', 'type' => 'rivalry'],
    570 => ['name' => 'Ratchet vs. Dr. Nefarious', 'type' => 'rivalry'],
    571 => ['name' => 'Ryu vs. Ken', 'type' => 'rivalry'],
    572 => ['name' => 'Fox McCloud vs. Wolf O\'Donnell', 'type' => 'rivalry'],
    573 => ['name' => 'Yuna vs. Seymour Guado', 'type' => 'rivalry'],
    574 => ['name' => 'Samus Aran vs. Ridley', 'type' => 'rivalry'],
    575 => ['name' => 'The Kid vs. The Guy', 'type' => 'rivalry'],
    576 => ['name' => 'Terra Branford vs. Kefka Palazzo', 'type' => 'rivalry'],
    577 => ['name' => 'Vyse vs. Galcian', 'type' => 'rivalry'],
    578 => ['name' => 'Chris Redfield vs. Albert Wesker', 'type' => 'rivalry'],
    579 => ['name' => 'Dan Hibiki vs. Sagat', 'type' => 'rivalry'],
    580 => ['name' => 'Big Boss vs. The Boss', 'type' => 'rivalry'],
    581 => ['name' => 'Tidus vs. Jecht', 'type' => 'rivalry'],
    582 => ['name' => 'Arthas vs. Illidan', 'type' => 'rivalry'],
    583 => ['name' => 'Link vs. Ganondorf', 'type' => 'rivalry'],
    584 => ['name' => 'Amaterasu vs. Orochi', 'type' => 'rivalry'],
    585 => ['name' => 'Tom Nook vs. Crazy Redd', 'type' => 'rivalry'],
    586 => ['name' => 'Meat Boy vs. Dr. Fetus', 'type' => 'rivalry'],
    587 => ['name' => 'Zidane Tribal vs. Kuja', 'type' => 'rivalry'],
    588 => ['name' => 'Banjo vs. Gruntilda', 'type' => 'rivalry'],
    589 => ['name' => 'Mega Man vs. Dr. Wily', 'type' => 'rivalry'],
    590 => ['name' => 'Gordon Freeman vs. Dr. Breen', 'type' => 'rivalry'],
    591 => ['name' => 'Phoenix Wright vs. Miles Edgeworth', 'type' => 'rivalry'],
    592 => ['name' => 'Alucard vs. Dracula', 'type' => 'rivalry'],
    593 => ['name' => 'Commander Shepard vs. Saren Arterius', 'type' => 'rivalry'],
    594 => ['name' => 'Chell vs. GLaDOS', 'type' => 'rivalry'],
    595 => ['name' => 'Ness vs. Giygas', 'type' => 'rivalry'],
    596 => ['name' => 'Frog vs. Magus', 'type' => 'rivalry'],
    597 => ['name' => 'Raiden vs. Vamp', 'type' => 'rivalry'],
    598 => ['name' => 'Cloud Strife vs. Sephiroth', 'type' => 'rivalry'],
    599 => ['name' => 'Lloyd Irving vs. Kratos Aurion', 'type' => 'rivalry'],
    600 => ['name' => 'Kratos vs. Zeus', 'type' => 'rivalry'],
    601 => ['name' => 'Professor Layton vs. Don Paolo', 'type' => 'rivalry'],
    602 => ['name' => 'Crash Bandicoot vs. Dr. Neo Cortex', 'type' => 'rivalry'],
    603 => ['name' => 'Pac-Man vs. Blinky', 'type' => 'rivalry'],
    604 => ['name' => 'Crono vs. Lavos', 'type' => 'rivalry'],
    605 => ['name' => 'Solid Snake vs. Liquid Snake', 'type' => 'rivalry'],
    606 => ['name' => 'Laharl vs. Mid-Boss', 'type' => 'rivalry'],
    607 => ['name' => 'Squall Leonhart vs. Seifer Almasy', 'type' => 'rivalry'],
    608 => ['name' => 'Ramza Beoulve vs. Delita Hyral', 'type' => 'rivalry'],
    609 => ['name' => 'Siegfried vs. Nightmare', 'type' => 'rivalry'],
    610 => ['name' => 'Dante vs. Vergil', 'type' => 'rivalry'],
    611 => ['name' => 'Sol Badguy vs. Ky Kiske', 'type' => 'rivalry'],
    612 => ['name' => 'Sora vs. Riku', 'type' => 'rivalry'],
    613 => ['name' => 'William B.J. Blazkowicz vs. Adolf', 'type' => 'rivalry'],

    /* ---- year (36): ids 752-787 ---- */
    752 => ['name' => '1979', 'type' => 'year'],
    753 => ['name' => '2009', 'type' => 'year'],
    754 => ['name' => '1983', 'type' => 'year'],
    755 => ['name' => '1989', 'type' => 'year'],
    756 => ['name' => '1981', 'type' => 'year'],
    757 => ['name' => '2006', 'type' => 'year'],
    758 => ['name' => '1978', 'type' => 'year'],
    759 => ['name' => '2005', 'type' => 'year'],
    760 => ['name' => '1986', 'type' => 'year'],
    761 => ['name' => '1995', 'type' => 'year'],
    762 => ['name' => '1985', 'type' => 'year'],
    763 => ['name' => '1987', 'type' => 'year'],
    764 => ['name' => '2001', 'type' => 'year'],
    765 => ['name' => '2014', 'type' => 'year'],
    766 => ['name' => '2008', 'type' => 'year'],
    767 => ['name' => '1997', 'type' => 'year'],
    768 => ['name' => '1999', 'type' => 'year'],
    769 => ['name' => '2007', 'type' => 'year'],
    770 => ['name' => '2012', 'type' => 'year'],
    771 => ['name' => '1990', 'type' => 'year'],
    772 => ['name' => '2000', 'type' => 'year'],
    773 => ['name' => '1996', 'type' => 'year'],
    774 => ['name' => '1988', 'type' => 'year'],
    775 => ['name' => '1991', 'type' => 'year'],
    776 => ['name' => '2002', 'type' => 'year'],
    777 => ['name' => '2010', 'type' => 'year'],
    778 => ['name' => '1994', 'type' => 'year'],
    779 => ['name' => '2004', 'type' => 'year'],
    780 => ['name' => '2011', 'type' => 'year'],
    781 => ['name' => '1993', 'type' => 'year'],
    782 => ['name' => '1998', 'type' => 'year'],
    783 => ['name' => '1992', 'type' => 'year'],
    784 => ['name' => '2016', 'type' => 'year'],
    785 => ['name' => '2003', 'type' => 'year'],
    786 => ['name' => '2013', 'type' => 'year'],
    787 => ['name' => '2015', 'type' => 'year'],
];

/** Look-alikes that must never collapse to one id. build-entrants.php asserts
 *  each group resolves to as many distinct ids as it has members. */
const ENTRANT_NEVER_MERGE = [
    ['Kratos', 'Kratos Aurion'],
    ['Big Boss', 'The Boss'],
    ['Isaac (Golden Sun)', 'Isaac (Binding)', 'Isaac Clarke'],
    ['Zero (Mega Man X)', 'Zero (999)'],
    ['Prince of All Cosmos', 'The King of All Cosmos'],
    ['Kain', 'Kain Highwind', 'Kaim Argonar'],
    ['Jade', 'Jade Curtiss'],
    ['Ryu', 'Ryu Hayabusa', 'Ryo Hazuki'],
    ['Link', 'Toon Link', 'Young Link', 'Classic Link', 'CD-I Link'],
    ['Pac-Man', 'Ms. Pac-Man'],
];

/** Bare alias variants that resolve safely only because one later contest spelled
 *  out every reading. build-entrants.php asserts the bare form is absent from that
 *  contest (so it can never be ambiguous there). */
const ENTRANT_ERA_SCOPED = [
    ['pool' => 'character', 'variant' => 'Isaac', 'disambiguated_in' => 'CB IX'],
    ['pool' => 'character', 'variant' => 'Zero', 'disambiguated_in' => 'CB IX'],
];

/** Placeholder strings that are not real entrants (skip, do not alias).
 *  Currently none reach data/contest-matches.json. */
const ENTRANT_NON = [];

/** Normalize a raw entrant string. Same contract as scripts/build-contest-matches.php ent(). */
function entrant_norm(string $s): string
{
    $s = html_entity_decode($s, ENT_QUOTES | ENT_HTML5);
    $s = str_replace("\u{2026}", '...', $s);
    $s = preg_replace('/\s+/', ' ', $s);

    return trim($s);
}

/** entrant_norm($name), then resolve it to its canonical form within $pool.
 *  Returns the normalized input unchanged when it is not a known alias. */
function entrant_canon(string $pool, string $name): string
{
    static $rev = null;
    if ($rev === null) {
        $rev = [];
        foreach (ENTRANT_ALIASES as $p => $map) {
            foreach ($map as $canon => $variants) {
                foreach ($variants as $v) {
                    $rev[$p][entrant_norm($v)] = $canon;
                }
            }
        }
    }

    $name = entrant_norm($name);

    return $rev[$pool][$name] ?? $name;
}
